/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * 
 * This file is generated by running: npx tsx scripts/generate-fillout-config.ts
 * 
 * Generated at: 2025-12-07T05:52:45.919Z
 * Database: Discover NoCode DB (aa7a307dc0a191a5)
 */

export interface TableConfig {
  id: string;
  fields: Record<string, string>; // field name -> field ID
}

export interface FilloutConfig {
  tables: Record<string, TableConfig>; // table name -> table config
}

/**
 * Fillout database configuration
 * Maps table names and field names to their IDs
 */
export const filloutConfig: FilloutConfig = {
  tables: {
    // Companies
    'Companies': {
      id: 'tbjujz4iq6r',
      fields: {
        'Name': 'fhChSupDLdT', // single_line_text
        'address': 'f9yAqGRFkyh', // single_line_text
        'contact_info': 'f1fH8ryDD2s', // single_line_text
        'Departments': 'fjMHFYFiwBR', // linked_record
        'Employees': 'ffbyM4nKuW1', // linked_record
      },
    },

    // Departments
    'Departments': {
      id: 'tviEhSR8rfg',
      fields: {
        'Name': 'fuuogs7EPK9', // single_line_text
        'company_id': 'fmCQWyoXnbn', // linked_record
        'Employees': 'frBEWxHtyRX', // linked_record
        'allow_memo_changes_without_approval': 'fpqSmCXBivA', // checkbox
        'pay_period_type': 'f9gdXM5bmV8', // single_select
        'pay_period_memo': 'f5pQa8sr1dK', // long_text
        'pay_period_start_days': 'f3uigucZcYN', // single_line_text
        'pay_period_end_days': 'f2AzfEujjnH', // single_line_text
        'payout_days': 'fupKweQXu8w', // single_line_text
        'Pay Periods': 'ftbc3KD6dx3', // linked_record
        'Pay Period Templates': 'fc5PiHHqveD', // linked_record
      },
    },

    // Employees
    'Employees': {
      id: 'tcNK2zZPcAR',
      fields: {
        'Name': 'f3K9qdNnRA9', // single_line_text
        'company_id': 'fuLkEWaHUgU', // linked_record
        'department_id': 'fmA8dSkHAfZ', // linked_record
        'email': 'f6ykZ6eBrne', // email
        'photo_url': 'fpFpVfgznC8', // url
        'timezone_id': 'fs2gtii1dEE', // linked_record
        'Employee Activity': 'f9YKuwZ4rWb', // linked_record
        'Client Employee Access': 'fm5mxcfbooJ', // linked_record
        'Time Cards': 'fhBykUFYCqx', // linked_record
        'Punches': 'fpfe7Fe1NGR', // linked_record
        'employment_type': 'ffB4MBjPDxo', // single_select
        'Employee Pay Rates': 'fwQPafpdmT1', // linked_record
        'Punch Alteration Requests': 'foQL5cB1vrL', // linked_record
        'Opportunities': 'fwfUm9wndnP', // linked_record
        'User App Access': 'f8zSdxRBZjh', // linked_record
        'User Permissions': 'fwx74KDtBDN', // linked_record
        'Views': 'fj47QZ2kAJ9', // linked_record
      },
    },

    // Employee Pay Rates
    'Employee Pay Rates': {
      id: 't4Va6eDRwTF',
      fields: {
        'Name': 'fcqjjrwvGeK', // single_line_text
        'employee_id': 'fjMtbBXAMfM', // linked_record
        'pay_rate': 'fs62EKDBAgC', // number
        'start_date': 'f6WQLNW7Mto', // date
        'end_date': 'f3ad2uTuBK8', // date
        'currency': 'feC5uhQa4mu', // single_select
      },
    },

    // Employee Activity
    'Employee Activity': {
      id: 't2JqUmLFqfA',
      fields: {
        'Name': 'fqRPQAxYage', // single_line_text
        'employee_id': 'fk1kZTuTQSr', // linked_record
        'start_date': 'fwafGdf92x4', // date
        'end_date': 'fvx9cxVNpfL', // date
        'status': 'fvHgcuUvxx5', // single_select
      },
    },

    // Clients
    'Clients': {
      id: 'te3Gw8PDkS7',
      fields: {
        'Name': 'fevakiE57vw', // single_line_text
        'contact_info': 'fx6LczTUAmt', // single_line_text
        'is_active': 'fivaGLvCUuL', // checkbox
        'Projects': 'f4eeKqzH83e', // linked_record
        'Client Employee Access': 'fmo7jVS8hnm', // linked_record
        'Time Cards': 'fjpbqeU41F4', // linked_record
        'Punches': 'f4ynefBYR8N', // linked_record
        'Client Invoices': 'fuLQYYeacy1', // linked_record
        'invoice_period_type': 'f77RZoSqHtN', // single_select
        'invoice_period_days': 'fgGwP9spFKV', // number
        'Opportunities': 'fsHaWTpr6NX', // linked_record
      },
    },

    // Opportunities
    'Opportunities': {
      id: 't3ephfTMjtf',
      fields: {
        'Name': 'f4JVByMmFDx', // single_line_text
        'Notes': 'fiMJReVJUYE', // long_text
        'Active': 'fsUMKqXrUX9', // checkbox
        'close_date': 'f6Bsu7ecv3v', // date
        'hours': 'fjmnaWZQXUL', // number
        'stage': 'foQUmc3ofy3', // single_select
        'status': 'frQQYH4HDVA', // single_select
        'client_id': 'f7NGuBA4ho4', // linked_record
        'owner_id': 'fiXqyvjQ33D', // linked_record
        'project_ids': 'fotMRetBniV', // linked_record
      },
    },

    // Client Invoices
    'Client Invoices': {
      id: 'trSRiSKg4h5',
      fields: {
        'Name': 'fthBuN4JVxz', // single_line_text
        'client_id': 'fiTeUnDDSyp', // linked_record
        'Punches': 'foCLeKCQFg3', // linked_record
        'collect_labor': 'f34Uxi53x6k', // checkbox
        'start_date': 'fr2kk34XSKu', // date
        'end_date': 'ffjjpVCN8By', // date
      },
    },

    // Client Employee Access
    'Client Employee Access': {
      id: 'tt5JxJuYHSQ',
      fields: {
        'Name': 'faLepfMyru8', // single_line_text
        'client_id': 'f681n9u8ovE', // linked_record
        'employee_id': 'fuhEsTwF8kJ', // linked_record
        'start_date': 'fmvF8Pmyqf3', // date
        'end_date': 'fo2k9La7cgp', // date
        'is_favorite': 'f8YLHRP43iL', // checkbox
      },
    },

    // Pay Periods
    'Pay Periods': {
      id: 'tk8fyCDXQ8H',
      fields: {
        'Name': 'fsr7BC4xJbd', // single_line_text
        'start_date': 'fwECZc4oRo6', // date
        'end_date': 'fm4qM76yjQM', // date
        'payout_date': 'f1GgZfoSsXF', // date
        'Time Cards': 'ftTokPcb5ZR', // linked_record
        'period_type': 'fmG8mtC9KtF', // single_select
        'department_id': 'fjnL221aCPk', // linked_record
      },
    },

    // Time Cards
    'Time Cards': {
      id: 't4F8J8DfSSN',
      fields: {
        'Name': 'fcq89thc4WH', // single_line_text
        'employee_id': 'fjysyYmr13B', // linked_record
        'pay_period_id': 'fscTy158mLF', // linked_record
        'client_id': 'f95r6ijCuWy', // linked_record
        'total_hours': 'fjSNgc1TDXh', // number
        'Punches': 'f5tFpPc3ikB', // linked_record
        'pay_period_start_date_lookup': 'fr6CRcg8zbe', // lookup
      },
    },

    // Punches
    'Punches': {
      id: 't3uPEDXn9wt',
      fields: {
        'Name': 'fuM8kRhk3w4', // single_line_text
        'employee_id': 'fdSxpJKx4UZ', // linked_record
        'client_id': 'f3ngEsiRxRx', // linked_record
        'project_ids': 'fh1m8AmFk5Q', // linked_record
        'time_card_id': 'fh3e7hZkxSw', // linked_record
        'memo': 'fpc6gXAfUX6', // long_text
        'Punch Alteration Requests': 'fx3N5KEEP4i', // linked_record
        'punch_in_time': 'f9ZJj4VR1mg', // datetime
        'punch_out_time': 'fb67e5tCCKB', // datetime
        'invoice_id': 'ffQbjUbMqHP', // linked_record
        'timezone_actual_id': 'fpwC9wNgLvN', // linked_record
        'punch_out_timezone_actual_id': 'f2rVKDarbn6', // linked_record
        'client_name': 'fb72dNX1c6i', // lookup
        'employee_name': 'fiPVb28e4ue', // lookup
      },
    },

    // Punch Alteration Requests
    'Punch Alteration Requests': {
      id: 't5x39cZnrdK',
      fields: {
        'Name': 'f8umtZcvS5D', // single_line_text
        'punch_id': 'f8SRmbKsKSr', // linked_record
        'new_project_ids': 'fuPdjeSUjT9', // linked_record
        'new_memo': 'fb4xHAu6BiD', // long_text
        'reason': 'f2t4xZJJe2r', // single_line_text
        'review_notes': 'fgvyiC5CRQR', // single_line_text
        'requested_at': 'f5BNjVbQPAh', // datetime
        'new_punch_in_time': 'ffriKCAHQNR', // datetime
        'new_punch_out_time': 'f34rnyQdGgC', // datetime
        'status': 'feNvSx9giZs', // single_select
        'reviewed_at': 'f14oZkQamMk', // datetime
        'employee_id': 'f3bJ8DuNhqj', // linked_record
        'new_timezone_actual_id': 'fkQQPqaGsj3', // linked_record
        'new_punch_out_timezone_actual_id': 'fkBQ6kQwhjp', // linked_record
      },
    },

    // Timezones
    'Timezones': {
      id: 'tbrgcTzKeZU',
      fields: {
        'Name': 'fbYMPgMrVJw', // single_line_text
        'iana_name': 'fmKQVpJMDCj', // single_line_text
        'Timezones Actual': 'fk89n72hzn3', // linked_record
        'Employees': 'frA3BtKHdYP', // linked_record
      },
    },

    // Timezones Actual
    'Timezones Actual': {
      id: 'tpgwfCYh9PH',
      fields: {
        'Name': 'fnbgYevVpfU', // single_line_text
        'timezone_id': 'f4a6h1ZHrAR', // linked_record
        'iana_name': 'frjRzHeZGQa', // single_line_text
        'offset_hours': 'fmA8DrkWB36', // number
        'is_dst': 'fkXh6HGaDTQ', // checkbox
        'Punches': 'f8XhzQLqLn6', // linked_record
        'Punches (1)': 'fu13bSCkMmF', // linked_record
        'Punch Alteration Requests': 'fnxJmSeu9pR', // linked_record
        'Punch Alteration Requests (1)': 'f9iHshuKXkR', // linked_record
      },
    },

    // Contracts
    'Contracts': {
      id: 'ta1vDzU6ZUm',
      fields: {
        'Name': 'faeoxaxoMFV', // single_line_text
        'Notes': 'ffRVKfeDRMu', // long_text
        'Active': 'f8QJ7DdcwuQ', // checkbox
      },
    },

    // Projects
    'Projects': {
      id: 't9gBZ2DumZM',
      fields: {
        'Name': 'f2T3kxrVuZe', // single_line_text
        'client_id': 'fncnHVJHvc8', // linked_record
        'is_active': 'fjH1ELHb8rX', // checkbox
        'Punches': 'f4BiUkzoWhd', // linked_record
        'Punch Alteration Requests': 'fpBGeKTaCMB', // linked_record
        'Opportunities': 'f2MDg1sBN9m', // linked_record
      },
    },

    // Tasks
    'Tasks': {
      id: 'toBcYFBgw7u',
      fields: {
        'Name': 'fiascPst5xt', // single_line_text
        'Notes': 'fv4LZnT11ua', // long_text
        'Active': 'fjbuqdjrCWr', // checkbox
      },
    },

    // Subtasks
    'Subtasks': {
      id: 't5kuJ3BNJLA',
      fields: {
        'Name': 'fuEf1dbrsnJ', // single_line_text
        'Notes': 'fpV9PLF8z85', // long_text
        'Active': 'fnrdCnDLdYv', // checkbox
      },
    },

    // Sprints
    'Sprints': {
      id: 'taWCNaKRfDZ',
      fields: {
        'Name': 'fjY33ZgbbY5', // single_line_text
        'Notes': 'fpVx3sRShXo', // long_text
        'Active': 'ff7c8PM4FfL', // checkbox
      },
    },

    // NoCode Leaders
    'NoCode Leaders': {
      id: 'trwubaBRu4W',
      fields: {
        'Name': 'fkr8MgD9nas', // single_line_text
        'Social/Webpages': 'fkFGzK7yRBT', // url
        'Focus': 'f5v6dwaQqsF', // multiple_select
        'Newsletter': 'fcyEWLZMCiu', // url
        'Profile Image': 'fnr4CmfkKPr', // attachments
        'Tool Expertise': 'fco1e6eNPza', // linked_record
        'Approved': 'fo5Cggomxgb', // checkbox
      },
    },

    // NoCode Tools
    'NoCode Tools': {
      id: 'tbRGciwF8sM',
      fields: {
        'Tool': 'fhYq77XLi4p', // single_line_text
        'Website': 'fh544vj7mBv', // url
        'Categories': 'frLjq1KUoUr', // multiple_select
        'Cost Limiter(s)': 'ff2Tx12qv2w', // multiple_select
        'Awards': 'f6TwsJ7L4bZ', // multiple_select
        'Approved': 'fgtHhw4Yj6T', // checkbox
        'NoCode Leaders': 'fbnK5Q7FzX8', // linked_record
      },
    },

    // NoCode Communities
    'NoCode Communities': {
      id: 'tfx9zy2okHB',
      fields: {
        'Community Name': 'fgbdLp5uxdX', // single_line_text
        'Supported Tools': 'f7H6EttW7cA', // single_line_text
        'Community Software': 'fqu8siUvbf4', // single_line_text
        'Community URL': 'f5EcrTiXK9d', // url
        'Tool Website': 'fb7s8Pp6RSf', // url
        'Approved': 'fqSMda223yE', // checkbox
        'Maintained By': 'fi8EFqKUcEm', // multiple_select
      },
    },

    // User App Access
    'User App Access': {
      id: 'tpwLPMUfiwS',
      fields: {
        'user_id': 'fjxC17QjGNE', // single_line_text
        'app_id': 'f2pYdazLcM5', // single_select
        'granted_at': 'ftJFGwaNDB5', // datetime
        'created_at': 'f4R2coME7hq', // datetime
        'updated_at': 'fswFX52XdFa', // datetime
        'employee_id': 'fjdE51bBqzV', // linked_record
      },
    },

    // User Permissions
    'User Permissions': {
      id: 't8bkw75uxCC',
      fields: {
        'user_id': 'f4CN1PshrnE', // single_line_text
        'app_id': 'f8oZ87SkQdv', // single_select
        'view_id': 'fbM9xJ84gde', // single_line_text
        'resource_type': 'frM5owmp1QY', // single_line_text
        'resource_id': 'fximm5mdpyK', // single_line_text
        'actions': 'fguFN1EUEZy', // multiple_select
        'created_at': 'fote5pqC8z5', // datetime
        'updated_at': 'f8xqbv6LRac', // datetime
        'employee_id': 'f7cmJVBDvHX', // linked_record
      },
    },

    // Views
    'Views': {
      id: 't1F3H9vT9Gr',
      fields: {
        'name': 'faN5cpwcJaK', // single_line_text
        'app_id': 'fuFGMggLKSN', // single_select
        'config': 'fbhWUpUoHBt', // long_text
        'description': 'fksJG7wqbCq', // long_text
        'is_default': 'fmLtkHkNzEf', // checkbox
        'is_custom': 'ffzWHnC5226', // checkbox
        'created_by': 'f2wpAXqn9Hv', // single_line_text
        'employee_id': 'f9oh2qLHw69', // linked_record
      },
    },

    // Pay Period Templates
    'Pay Period Templates': {
      id: 't7RLTQD7xWd',
      fields: {
        'Name': 'fcTwZrzCV3s', // single_line_text
        'department_id': 'fiunMgBrrC9', // linked_record
        'period_number': 'faiQsBfwJtT', // number
        'start_day': 'fjkdULQiY68', // number
        'end_day': 'f6GFoDwhiuS', // number
        'payout_day': 'fn8tD3dpDnQ', // single_line_text
        'payout_month_offset': 'fxzeXzvBGt2', // number
        'is_active': 'f26NBqb2bqj', // checkbox
      },
    },

  },
};

/**
 * Table ID constants
 * Generated from Fillout database schema
 */
export const TABLE_COMPANIES_ID = 'tbjujz4iq6r'; // Companies
export const TABLE_DEPARTMENTS_ID = 'tviEhSR8rfg'; // Departments
export const TABLE_EMPLOYEES_ID = 'tcNK2zZPcAR'; // Employees
export const TABLE_EMPLOYEE_PAY_RATES_ID = 't4Va6eDRwTF'; // Employee Pay Rates
export const TABLE_EMPLOYEE_ACTIVITY_ID = 't2JqUmLFqfA'; // Employee Activity
export const TABLE_CLIENTS_ID = 'te3Gw8PDkS7'; // Clients
export const TABLE_OPPORTUNITIES_ID = 't3ephfTMjtf'; // Opportunities
export const TABLE_CLIENT_INVOICES_ID = 'trSRiSKg4h5'; // Client Invoices
export const TABLE_CLIENT_EMPLOYEE_ACCESS_ID = 'tt5JxJuYHSQ'; // Client Employee Access
export const TABLE_PAY_PERIODS_ID = 'tk8fyCDXQ8H'; // Pay Periods
export const TABLE_TIME_CARDS_ID = 't4F8J8DfSSN'; // Time Cards
export const TABLE_PUNCHES_ID = 't3uPEDXn9wt'; // Punches
export const TABLE_PUNCH_ALTERATION_REQUESTS_ID = 't5x39cZnrdK'; // Punch Alteration Requests
export const TABLE_TIMEZONES_ID = 'tbrgcTzKeZU'; // Timezones
export const TABLE_TIMEZONES_ACTUAL_ID = 'tpgwfCYh9PH'; // Timezones Actual
export const TABLE_CONTRACTS_ID = 'ta1vDzU6ZUm'; // Contracts
export const TABLE_PROJECTS_ID = 't9gBZ2DumZM'; // Projects
export const TABLE_TASKS_ID = 'toBcYFBgw7u'; // Tasks
export const TABLE_SUBTASKS_ID = 't5kuJ3BNJLA'; // Subtasks
export const TABLE_SPRINTS_ID = 'taWCNaKRfDZ'; // Sprints
export const TABLE_NOCODE_LEADERS_ID = 'trwubaBRu4W'; // NoCode Leaders
export const TABLE_NOCODE_TOOLS_ID = 'tbRGciwF8sM'; // NoCode Tools
export const TABLE_NOCODE_COMMUNITIES_ID = 'tfx9zy2okHB'; // NoCode Communities
export const TABLE_USER_APP_ACCESS_ID = 'tpwLPMUfiwS'; // User App Access
export const TABLE_USER_PERMISSIONS_ID = 't8bkw75uxCC'; // User Permissions
export const TABLE_VIEWS_ID = 't1F3H9vT9Gr'; // Views
export const TABLE_PAY_PERIOD_TEMPLATES_ID = 't7RLTQD7xWd'; // Pay Period Templates

/**
 * Field ID constants
 * Generated from Fillout database schema
 * Format: TABLE_NAME_FIELD_NAME_FIELD_ID
 */
// Companies fields
export const COMPANIES_NAME_FIELD_ID = 'fhChSupDLdT'; // Companies.Name (single_line_text)
export const COMPANIES_ADDRESS_FIELD_ID = 'f9yAqGRFkyh'; // Companies.address (single_line_text)
export const COMPANIES_CONTACT_INFO_FIELD_ID = 'f1fH8ryDD2s'; // Companies.contact_info (single_line_text)
export const COMPANIES_DEPARTMENTS_FIELD_ID = 'fjMHFYFiwBR'; // Companies.Departments (linked_record)
export const COMPANIES_EMPLOYEES_FIELD_ID = 'ffbyM4nKuW1'; // Companies.Employees (linked_record)

// Departments fields
export const DEPARTMENTS_NAME_FIELD_ID = 'fuuogs7EPK9'; // Departments.Name (single_line_text)
export const DEPARTMENTS_COMPANY_ID_FIELD_ID = 'fmCQWyoXnbn'; // Departments.company_id (linked_record)
export const DEPARTMENTS_EMPLOYEES_FIELD_ID = 'frBEWxHtyRX'; // Departments.Employees (linked_record)
export const DEPARTMENTS_ALLOW_MEMO_CHANGES_WITHOUT_APPROVAL_FIELD_ID = 'fpqSmCXBivA'; // Departments.allow_memo_changes_without_approval (checkbox)
export const DEPARTMENTS_PAY_PERIOD_TYPE_FIELD_ID = 'f9gdXM5bmV8'; // Departments.pay_period_type (single_select)
export const DEPARTMENTS_PAY_PERIOD_MEMO_FIELD_ID = 'f5pQa8sr1dK'; // Departments.pay_period_memo (long_text)
export const DEPARTMENTS_PAY_PERIOD_START_DAYS_FIELD_ID = 'f3uigucZcYN'; // Departments.pay_period_start_days (single_line_text)
export const DEPARTMENTS_PAY_PERIOD_END_DAYS_FIELD_ID = 'f2AzfEujjnH'; // Departments.pay_period_end_days (single_line_text)
export const DEPARTMENTS_PAYOUT_DAYS_FIELD_ID = 'fupKweQXu8w'; // Departments.payout_days (single_line_text)
export const DEPARTMENTS_PAY_PERIODS_FIELD_ID = 'ftbc3KD6dx3'; // Departments.Pay Periods (linked_record)
export const DEPARTMENTS_PAY_PERIOD_TEMPLATES_FIELD_ID = 'fc5PiHHqveD'; // Departments.Pay Period Templates (linked_record)

// Employees fields
export const EMPLOYEES_NAME_FIELD_ID = 'f3K9qdNnRA9'; // Employees.Name (single_line_text)
export const EMPLOYEES_COMPANY_ID_FIELD_ID = 'fuLkEWaHUgU'; // Employees.company_id (linked_record)
export const EMPLOYEES_DEPARTMENT_ID_FIELD_ID = 'fmA8dSkHAfZ'; // Employees.department_id (linked_record)
export const EMPLOYEES_EMAIL_FIELD_ID = 'f6ykZ6eBrne'; // Employees.email (email)
export const EMPLOYEES_PHOTO_URL_FIELD_ID = 'fpFpVfgznC8'; // Employees.photo_url (url)
export const EMPLOYEES_TIMEZONE_ID_FIELD_ID = 'fs2gtii1dEE'; // Employees.timezone_id (linked_record)
export const EMPLOYEES_EMPLOYEE_ACTIVITY_FIELD_ID = 'f9YKuwZ4rWb'; // Employees.Employee Activity (linked_record)
export const EMPLOYEES_CLIENT_EMPLOYEE_ACCESS_FIELD_ID = 'fm5mxcfbooJ'; // Employees.Client Employee Access (linked_record)
export const EMPLOYEES_TIME_CARDS_FIELD_ID = 'fhBykUFYCqx'; // Employees.Time Cards (linked_record)
export const EMPLOYEES_PUNCHES_FIELD_ID = 'fpfe7Fe1NGR'; // Employees.Punches (linked_record)
export const EMPLOYEES_EMPLOYMENT_TYPE_FIELD_ID = 'ffB4MBjPDxo'; // Employees.employment_type (single_select)
export const EMPLOYEES_EMPLOYEE_PAY_RATES_FIELD_ID = 'fwQPafpdmT1'; // Employees.Employee Pay Rates (linked_record)
export const EMPLOYEES_PUNCH_ALTERATION_REQUESTS_FIELD_ID = 'foQL5cB1vrL'; // Employees.Punch Alteration Requests (linked_record)
export const EMPLOYEES_OPPORTUNITIES_FIELD_ID = 'fwfUm9wndnP'; // Employees.Opportunities (linked_record)
export const EMPLOYEES_USER_APP_ACCESS_FIELD_ID = 'f8zSdxRBZjh'; // Employees.User App Access (linked_record)
export const EMPLOYEES_USER_PERMISSIONS_FIELD_ID = 'fwx74KDtBDN'; // Employees.User Permissions (linked_record)
export const EMPLOYEES_VIEWS_FIELD_ID = 'fj47QZ2kAJ9'; // Employees.Views (linked_record)

// Employee Pay Rates fields
export const EMPLOYEE_PAY_RATES_NAME_FIELD_ID = 'fcqjjrwvGeK'; // Employee Pay Rates.Name (single_line_text)
export const EMPLOYEE_PAY_RATES_EMPLOYEE_ID_FIELD_ID = 'fjMtbBXAMfM'; // Employee Pay Rates.employee_id (linked_record)
export const EMPLOYEE_PAY_RATES_PAY_RATE_FIELD_ID = 'fs62EKDBAgC'; // Employee Pay Rates.pay_rate (number)
export const EMPLOYEE_PAY_RATES_START_DATE_FIELD_ID = 'f6WQLNW7Mto'; // Employee Pay Rates.start_date (date)
export const EMPLOYEE_PAY_RATES_END_DATE_FIELD_ID = 'f3ad2uTuBK8'; // Employee Pay Rates.end_date (date)
export const EMPLOYEE_PAY_RATES_CURRENCY_FIELD_ID = 'feC5uhQa4mu'; // Employee Pay Rates.currency (single_select)

// Employee Activity fields
export const EMPLOYEE_ACTIVITY_NAME_FIELD_ID = 'fqRPQAxYage'; // Employee Activity.Name (single_line_text)
export const EMPLOYEE_ACTIVITY_EMPLOYEE_ID_FIELD_ID = 'fk1kZTuTQSr'; // Employee Activity.employee_id (linked_record)
export const EMPLOYEE_ACTIVITY_START_DATE_FIELD_ID = 'fwafGdf92x4'; // Employee Activity.start_date (date)
export const EMPLOYEE_ACTIVITY_END_DATE_FIELD_ID = 'fvx9cxVNpfL'; // Employee Activity.end_date (date)
export const EMPLOYEE_ACTIVITY_STATUS_FIELD_ID = 'fvHgcuUvxx5'; // Employee Activity.status (single_select)

// Clients fields
export const CLIENTS_NAME_FIELD_ID = 'fevakiE57vw'; // Clients.Name (single_line_text)
export const CLIENTS_CONTACT_INFO_FIELD_ID = 'fx6LczTUAmt'; // Clients.contact_info (single_line_text)
export const CLIENTS_IS_ACTIVE_FIELD_ID = 'fivaGLvCUuL'; // Clients.is_active (checkbox)
export const CLIENTS_PROJECTS_FIELD_ID = 'f4eeKqzH83e'; // Clients.Projects (linked_record)
export const CLIENTS_CLIENT_EMPLOYEE_ACCESS_FIELD_ID = 'fmo7jVS8hnm'; // Clients.Client Employee Access (linked_record)
export const CLIENTS_TIME_CARDS_FIELD_ID = 'fjpbqeU41F4'; // Clients.Time Cards (linked_record)
export const CLIENTS_PUNCHES_FIELD_ID = 'f4ynefBYR8N'; // Clients.Punches (linked_record)
export const CLIENTS_CLIENT_INVOICES_FIELD_ID = 'fuLQYYeacy1'; // Clients.Client Invoices (linked_record)
export const CLIENTS_INVOICE_PERIOD_TYPE_FIELD_ID = 'f77RZoSqHtN'; // Clients.invoice_period_type (single_select)
export const CLIENTS_INVOICE_PERIOD_DAYS_FIELD_ID = 'fgGwP9spFKV'; // Clients.invoice_period_days (number)
export const CLIENTS_OPPORTUNITIES_FIELD_ID = 'fsHaWTpr6NX'; // Clients.Opportunities (linked_record)

// Opportunities fields
export const OPPORTUNITIES_NAME_FIELD_ID = 'f4JVByMmFDx'; // Opportunities.Name (single_line_text)
export const OPPORTUNITIES_NOTES_FIELD_ID = 'fiMJReVJUYE'; // Opportunities.Notes (long_text)
export const OPPORTUNITIES_ACTIVE_FIELD_ID = 'fsUMKqXrUX9'; // Opportunities.Active (checkbox)
export const OPPORTUNITIES_CLOSE_DATE_FIELD_ID = 'f6Bsu7ecv3v'; // Opportunities.close_date (date)
export const OPPORTUNITIES_HOURS_FIELD_ID = 'fjmnaWZQXUL'; // Opportunities.hours (number)
export const OPPORTUNITIES_STAGE_FIELD_ID = 'foQUmc3ofy3'; // Opportunities.stage (single_select)
export const OPPORTUNITIES_STATUS_FIELD_ID = 'frQQYH4HDVA'; // Opportunities.status (single_select)
export const OPPORTUNITIES_CLIENT_ID_FIELD_ID = 'f7NGuBA4ho4'; // Opportunities.client_id (linked_record)
export const OPPORTUNITIES_OWNER_ID_FIELD_ID = 'fiXqyvjQ33D'; // Opportunities.owner_id (linked_record)
export const OPPORTUNITIES_PROJECT_IDS_FIELD_ID = 'fotMRetBniV'; // Opportunities.project_ids (linked_record)

// Client Invoices fields
export const CLIENT_INVOICES_NAME_FIELD_ID = 'fthBuN4JVxz'; // Client Invoices.Name (single_line_text)
export const CLIENT_INVOICES_CLIENT_ID_FIELD_ID = 'fiTeUnDDSyp'; // Client Invoices.client_id (linked_record)
export const CLIENT_INVOICES_PUNCHES_FIELD_ID = 'foCLeKCQFg3'; // Client Invoices.Punches (linked_record)
export const CLIENT_INVOICES_COLLECT_LABOR_FIELD_ID = 'f34Uxi53x6k'; // Client Invoices.collect_labor (checkbox)
export const CLIENT_INVOICES_START_DATE_FIELD_ID = 'fr2kk34XSKu'; // Client Invoices.start_date (date)
export const CLIENT_INVOICES_END_DATE_FIELD_ID = 'ffjjpVCN8By'; // Client Invoices.end_date (date)

// Client Employee Access fields
export const CLIENT_EMPLOYEE_ACCESS_NAME_FIELD_ID = 'faLepfMyru8'; // Client Employee Access.Name (single_line_text)
export const CLIENT_EMPLOYEE_ACCESS_CLIENT_ID_FIELD_ID = 'f681n9u8ovE'; // Client Employee Access.client_id (linked_record)
export const CLIENT_EMPLOYEE_ACCESS_EMPLOYEE_ID_FIELD_ID = 'fuhEsTwF8kJ'; // Client Employee Access.employee_id (linked_record)
export const CLIENT_EMPLOYEE_ACCESS_START_DATE_FIELD_ID = 'fmvF8Pmyqf3'; // Client Employee Access.start_date (date)
export const CLIENT_EMPLOYEE_ACCESS_END_DATE_FIELD_ID = 'fo2k9La7cgp'; // Client Employee Access.end_date (date)
export const CLIENT_EMPLOYEE_ACCESS_IS_FAVORITE_FIELD_ID = 'f8YLHRP43iL'; // Client Employee Access.is_favorite (checkbox)

// Pay Periods fields
export const PAY_PERIODS_NAME_FIELD_ID = 'fsr7BC4xJbd'; // Pay Periods.Name (single_line_text)
export const PAY_PERIODS_START_DATE_FIELD_ID = 'fwECZc4oRo6'; // Pay Periods.start_date (date)
export const PAY_PERIODS_END_DATE_FIELD_ID = 'fm4qM76yjQM'; // Pay Periods.end_date (date)
export const PAY_PERIODS_PAYOUT_DATE_FIELD_ID = 'f1GgZfoSsXF'; // Pay Periods.payout_date (date)
export const PAY_PERIODS_TIME_CARDS_FIELD_ID = 'ftTokPcb5ZR'; // Pay Periods.Time Cards (linked_record)
export const PAY_PERIODS_PERIOD_TYPE_FIELD_ID = 'fmG8mtC9KtF'; // Pay Periods.period_type (single_select)
export const PAY_PERIODS_DEPARTMENT_ID_FIELD_ID = 'fjnL221aCPk'; // Pay Periods.department_id (linked_record)

// Time Cards fields
export const TIME_CARDS_NAME_FIELD_ID = 'fcq89thc4WH'; // Time Cards.Name (single_line_text)
export const TIME_CARDS_EMPLOYEE_ID_FIELD_ID = 'fjysyYmr13B'; // Time Cards.employee_id (linked_record)
export const TIME_CARDS_PAY_PERIOD_ID_FIELD_ID = 'fscTy158mLF'; // Time Cards.pay_period_id (linked_record)
export const TIME_CARDS_CLIENT_ID_FIELD_ID = 'f95r6ijCuWy'; // Time Cards.client_id (linked_record)
export const TIME_CARDS_TOTAL_HOURS_FIELD_ID = 'fjSNgc1TDXh'; // Time Cards.total_hours (number)
export const TIME_CARDS_PUNCHES_FIELD_ID = 'f5tFpPc3ikB'; // Time Cards.Punches (linked_record)
export const TIME_CARDS_PAY_PERIOD_START_DATE_LOOKUP_FIELD_ID = 'fr6CRcg8zbe'; // Time Cards.pay_period_start_date_lookup (lookup)

// Punches fields
export const PUNCHES_NAME_FIELD_ID = 'fuM8kRhk3w4'; // Punches.Name (single_line_text)
export const PUNCHES_EMPLOYEE_ID_FIELD_ID = 'fdSxpJKx4UZ'; // Punches.employee_id (linked_record)
export const PUNCHES_CLIENT_ID_FIELD_ID = 'f3ngEsiRxRx'; // Punches.client_id (linked_record)
export const PUNCHES_PROJECT_IDS_FIELD_ID = 'fh1m8AmFk5Q'; // Punches.project_ids (linked_record)
export const PUNCHES_TIME_CARD_ID_FIELD_ID = 'fh3e7hZkxSw'; // Punches.time_card_id (linked_record)
export const PUNCHES_MEMO_FIELD_ID = 'fpc6gXAfUX6'; // Punches.memo (long_text)
export const PUNCHES_PUNCH_ALTERATION_REQUESTS_FIELD_ID = 'fx3N5KEEP4i'; // Punches.Punch Alteration Requests (linked_record)
export const PUNCHES_PUNCH_IN_TIME_FIELD_ID = 'f9ZJj4VR1mg'; // Punches.punch_in_time (datetime)
export const PUNCHES_PUNCH_OUT_TIME_FIELD_ID = 'fb67e5tCCKB'; // Punches.punch_out_time (datetime)
export const PUNCHES_INVOICE_ID_FIELD_ID = 'ffQbjUbMqHP'; // Punches.invoice_id (linked_record)
export const PUNCHES_TIMEZONE_ACTUAL_ID_FIELD_ID = 'fpwC9wNgLvN'; // Punches.timezone_actual_id (linked_record)
export const PUNCHES_PUNCH_OUT_TIMEZONE_ACTUAL_ID_FIELD_ID = 'f2rVKDarbn6'; // Punches.punch_out_timezone_actual_id (linked_record)
export const PUNCHES_CLIENT_NAME_FIELD_ID = 'fb72dNX1c6i'; // Punches.client_name (lookup)
export const PUNCHES_EMPLOYEE_NAME_FIELD_ID = 'fiPVb28e4ue'; // Punches.employee_name (lookup)

// Punch Alteration Requests fields
export const PUNCH_ALTERATION_REQUESTS_NAME_FIELD_ID = 'f8umtZcvS5D'; // Punch Alteration Requests.Name (single_line_text)
export const PUNCH_ALTERATION_REQUESTS_PUNCH_ID_FIELD_ID = 'f8SRmbKsKSr'; // Punch Alteration Requests.punch_id (linked_record)
export const PUNCH_ALTERATION_REQUESTS_NEW_PROJECT_IDS_FIELD_ID = 'fuPdjeSUjT9'; // Punch Alteration Requests.new_project_ids (linked_record)
export const PUNCH_ALTERATION_REQUESTS_NEW_MEMO_FIELD_ID = 'fb4xHAu6BiD'; // Punch Alteration Requests.new_memo (long_text)
export const PUNCH_ALTERATION_REQUESTS_REASON_FIELD_ID = 'f2t4xZJJe2r'; // Punch Alteration Requests.reason (single_line_text)
export const PUNCH_ALTERATION_REQUESTS_REVIEW_NOTES_FIELD_ID = 'fgvyiC5CRQR'; // Punch Alteration Requests.review_notes (single_line_text)
export const PUNCH_ALTERATION_REQUESTS_REQUESTED_AT_FIELD_ID = 'f5BNjVbQPAh'; // Punch Alteration Requests.requested_at (datetime)
export const PUNCH_ALTERATION_REQUESTS_NEW_PUNCH_IN_TIME_FIELD_ID = 'ffriKCAHQNR'; // Punch Alteration Requests.new_punch_in_time (datetime)
export const PUNCH_ALTERATION_REQUESTS_NEW_PUNCH_OUT_TIME_FIELD_ID = 'f34rnyQdGgC'; // Punch Alteration Requests.new_punch_out_time (datetime)
export const PUNCH_ALTERATION_REQUESTS_STATUS_FIELD_ID = 'feNvSx9giZs'; // Punch Alteration Requests.status (single_select)
export const PUNCH_ALTERATION_REQUESTS_REVIEWED_AT_FIELD_ID = 'f14oZkQamMk'; // Punch Alteration Requests.reviewed_at (datetime)
export const PUNCH_ALTERATION_REQUESTS_EMPLOYEE_ID_FIELD_ID = 'f3bJ8DuNhqj'; // Punch Alteration Requests.employee_id (linked_record)
export const PUNCH_ALTERATION_REQUESTS_NEW_TIMEZONE_ACTUAL_ID_FIELD_ID = 'fkQQPqaGsj3'; // Punch Alteration Requests.new_timezone_actual_id (linked_record)
export const PUNCH_ALTERATION_REQUESTS_NEW_PUNCH_OUT_TIMEZONE_ACTUAL_ID_FIELD_ID = 'fkBQ6kQwhjp'; // Punch Alteration Requests.new_punch_out_timezone_actual_id (linked_record)

// Timezones fields
export const TIMEZONES_NAME_FIELD_ID = 'fbYMPgMrVJw'; // Timezones.Name (single_line_text)
export const TIMEZONES_IANA_NAME_FIELD_ID = 'fmKQVpJMDCj'; // Timezones.iana_name (single_line_text)
export const TIMEZONES_TIMEZONES_ACTUAL_FIELD_ID = 'fk89n72hzn3'; // Timezones.Timezones Actual (linked_record)
export const TIMEZONES_EMPLOYEES_FIELD_ID = 'frA3BtKHdYP'; // Timezones.Employees (linked_record)

// Timezones Actual fields
export const TIMEZONES_ACTUAL_NAME_FIELD_ID = 'fnbgYevVpfU'; // Timezones Actual.Name (single_line_text)
export const TIMEZONES_ACTUAL_TIMEZONE_ID_FIELD_ID = 'f4a6h1ZHrAR'; // Timezones Actual.timezone_id (linked_record)
export const TIMEZONES_ACTUAL_IANA_NAME_FIELD_ID = 'frjRzHeZGQa'; // Timezones Actual.iana_name (single_line_text)
export const TIMEZONES_ACTUAL_OFFSET_HOURS_FIELD_ID = 'fmA8DrkWB36'; // Timezones Actual.offset_hours (number)
export const TIMEZONES_ACTUAL_IS_DST_FIELD_ID = 'fkXh6HGaDTQ'; // Timezones Actual.is_dst (checkbox)
export const TIMEZONES_ACTUAL_PUNCHES_FIELD_ID = 'f8XhzQLqLn6'; // Timezones Actual.Punches (linked_record)
export const TIMEZONES_ACTUAL_PUNCHES_1_FIELD_ID = 'fu13bSCkMmF'; // Timezones Actual.Punches (1) (linked_record)
export const TIMEZONES_ACTUAL_PUNCH_ALTERATION_REQUESTS_FIELD_ID = 'fnxJmSeu9pR'; // Timezones Actual.Punch Alteration Requests (linked_record)
export const TIMEZONES_ACTUAL_PUNCH_ALTERATION_REQUESTS_1_FIELD_ID = 'f9iHshuKXkR'; // Timezones Actual.Punch Alteration Requests (1) (linked_record)

// Contracts fields
export const CONTRACTS_NAME_FIELD_ID = 'faeoxaxoMFV'; // Contracts.Name (single_line_text)
export const CONTRACTS_NOTES_FIELD_ID = 'ffRVKfeDRMu'; // Contracts.Notes (long_text)
export const CONTRACTS_ACTIVE_FIELD_ID = 'f8QJ7DdcwuQ'; // Contracts.Active (checkbox)

// Projects fields
export const PROJECTS_NAME_FIELD_ID = 'f2T3kxrVuZe'; // Projects.Name (single_line_text)
export const PROJECTS_CLIENT_ID_FIELD_ID = 'fncnHVJHvc8'; // Projects.client_id (linked_record)
export const PROJECTS_IS_ACTIVE_FIELD_ID = 'fjH1ELHb8rX'; // Projects.is_active (checkbox)
export const PROJECTS_PUNCHES_FIELD_ID = 'f4BiUkzoWhd'; // Projects.Punches (linked_record)
export const PROJECTS_PUNCH_ALTERATION_REQUESTS_FIELD_ID = 'fpBGeKTaCMB'; // Projects.Punch Alteration Requests (linked_record)
export const PROJECTS_OPPORTUNITIES_FIELD_ID = 'f2MDg1sBN9m'; // Projects.Opportunities (linked_record)

// Tasks fields
export const TASKS_NAME_FIELD_ID = 'fiascPst5xt'; // Tasks.Name (single_line_text)
export const TASKS_NOTES_FIELD_ID = 'fv4LZnT11ua'; // Tasks.Notes (long_text)
export const TASKS_ACTIVE_FIELD_ID = 'fjbuqdjrCWr'; // Tasks.Active (checkbox)

// Subtasks fields
export const SUBTASKS_NAME_FIELD_ID = 'fuEf1dbrsnJ'; // Subtasks.Name (single_line_text)
export const SUBTASKS_NOTES_FIELD_ID = 'fpV9PLF8z85'; // Subtasks.Notes (long_text)
export const SUBTASKS_ACTIVE_FIELD_ID = 'fnrdCnDLdYv'; // Subtasks.Active (checkbox)

// Sprints fields
export const SPRINTS_NAME_FIELD_ID = 'fjY33ZgbbY5'; // Sprints.Name (single_line_text)
export const SPRINTS_NOTES_FIELD_ID = 'fpVx3sRShXo'; // Sprints.Notes (long_text)
export const SPRINTS_ACTIVE_FIELD_ID = 'ff7c8PM4FfL'; // Sprints.Active (checkbox)

// NoCode Leaders fields
export const NOCODE_LEADERS_NAME_FIELD_ID = 'fkr8MgD9nas'; // NoCode Leaders.Name (single_line_text)
export const NOCODE_LEADERS_SOCIAL_WEBPAGES_FIELD_ID = 'fkFGzK7yRBT'; // NoCode Leaders.Social/Webpages (url)
export const NOCODE_LEADERS_FOCUS_FIELD_ID = 'f5v6dwaQqsF'; // NoCode Leaders.Focus (multiple_select)
export const NOCODE_LEADERS_NEWSLETTER_FIELD_ID = 'fcyEWLZMCiu'; // NoCode Leaders.Newsletter (url)
export const NOCODE_LEADERS_PROFILE_IMAGE_FIELD_ID = 'fnr4CmfkKPr'; // NoCode Leaders.Profile Image (attachments)
export const NOCODE_LEADERS_TOOL_EXPERTISE_FIELD_ID = 'fco1e6eNPza'; // NoCode Leaders.Tool Expertise (linked_record)
export const NOCODE_LEADERS_APPROVED_FIELD_ID = 'fo5Cggomxgb'; // NoCode Leaders.Approved (checkbox)

// NoCode Tools fields
export const NOCODE_TOOLS_TOOL_FIELD_ID = 'fhYq77XLi4p'; // NoCode Tools.Tool (single_line_text)
export const NOCODE_TOOLS_WEBSITE_FIELD_ID = 'fh544vj7mBv'; // NoCode Tools.Website (url)
export const NOCODE_TOOLS_CATEGORIES_FIELD_ID = 'frLjq1KUoUr'; // NoCode Tools.Categories (multiple_select)
export const NOCODE_TOOLS_COST_LIMITER_S_FIELD_ID = 'ff2Tx12qv2w'; // NoCode Tools.Cost Limiter(s) (multiple_select)
export const NOCODE_TOOLS_AWARDS_FIELD_ID = 'f6TwsJ7L4bZ'; // NoCode Tools.Awards (multiple_select)
export const NOCODE_TOOLS_APPROVED_FIELD_ID = 'fgtHhw4Yj6T'; // NoCode Tools.Approved (checkbox)
export const NOCODE_TOOLS_NOCODE_LEADERS_FIELD_ID = 'fbnK5Q7FzX8'; // NoCode Tools.NoCode Leaders (linked_record)

// NoCode Communities fields
export const NOCODE_COMMUNITIES_COMMUNITY_NAME_FIELD_ID = 'fgbdLp5uxdX'; // NoCode Communities.Community Name (single_line_text)
export const NOCODE_COMMUNITIES_SUPPORTED_TOOLS_FIELD_ID = 'f7H6EttW7cA'; // NoCode Communities.Supported Tools (single_line_text)
export const NOCODE_COMMUNITIES_COMMUNITY_SOFTWARE_FIELD_ID = 'fqu8siUvbf4'; // NoCode Communities.Community Software (single_line_text)
export const NOCODE_COMMUNITIES_COMMUNITY_URL_FIELD_ID = 'f5EcrTiXK9d'; // NoCode Communities.Community URL (url)
export const NOCODE_COMMUNITIES_TOOL_WEBSITE_FIELD_ID = 'fb7s8Pp6RSf'; // NoCode Communities.Tool Website (url)
export const NOCODE_COMMUNITIES_APPROVED_FIELD_ID = 'fqSMda223yE'; // NoCode Communities.Approved (checkbox)
export const NOCODE_COMMUNITIES_MAINTAINED_BY_FIELD_ID = 'fi8EFqKUcEm'; // NoCode Communities.Maintained By (multiple_select)

// User App Access fields
export const USER_APP_ACCESS_USER_ID_FIELD_ID = 'fjxC17QjGNE'; // User App Access.user_id (single_line_text)
export const USER_APP_ACCESS_APP_ID_FIELD_ID = 'f2pYdazLcM5'; // User App Access.app_id (single_select)
export const USER_APP_ACCESS_GRANTED_AT_FIELD_ID = 'ftJFGwaNDB5'; // User App Access.granted_at (datetime)
export const USER_APP_ACCESS_CREATED_AT_FIELD_ID = 'f4R2coME7hq'; // User App Access.created_at (datetime)
export const USER_APP_ACCESS_UPDATED_AT_FIELD_ID = 'fswFX52XdFa'; // User App Access.updated_at (datetime)
export const USER_APP_ACCESS_EMPLOYEE_ID_FIELD_ID = 'fjdE51bBqzV'; // User App Access.employee_id (linked_record)

// User Permissions fields
export const USER_PERMISSIONS_USER_ID_FIELD_ID = 'f4CN1PshrnE'; // User Permissions.user_id (single_line_text)
export const USER_PERMISSIONS_APP_ID_FIELD_ID = 'f8oZ87SkQdv'; // User Permissions.app_id (single_select)
export const USER_PERMISSIONS_VIEW_ID_FIELD_ID = 'fbM9xJ84gde'; // User Permissions.view_id (single_line_text)
export const USER_PERMISSIONS_RESOURCE_TYPE_FIELD_ID = 'frM5owmp1QY'; // User Permissions.resource_type (single_line_text)
export const USER_PERMISSIONS_RESOURCE_ID_FIELD_ID = 'fximm5mdpyK'; // User Permissions.resource_id (single_line_text)
export const USER_PERMISSIONS_ACTIONS_FIELD_ID = 'fguFN1EUEZy'; // User Permissions.actions (multiple_select)
export const USER_PERMISSIONS_CREATED_AT_FIELD_ID = 'fote5pqC8z5'; // User Permissions.created_at (datetime)
export const USER_PERMISSIONS_UPDATED_AT_FIELD_ID = 'f8xqbv6LRac'; // User Permissions.updated_at (datetime)
export const USER_PERMISSIONS_EMPLOYEE_ID_FIELD_ID = 'f7cmJVBDvHX'; // User Permissions.employee_id (linked_record)

// Views fields
export const VIEWS_NAME_FIELD_ID = 'faN5cpwcJaK'; // Views.name (single_line_text)
export const VIEWS_APP_ID_FIELD_ID = 'fuFGMggLKSN'; // Views.app_id (single_select)
export const VIEWS_CONFIG_FIELD_ID = 'fbhWUpUoHBt'; // Views.config (long_text)
export const VIEWS_DESCRIPTION_FIELD_ID = 'fksJG7wqbCq'; // Views.description (long_text)
export const VIEWS_IS_DEFAULT_FIELD_ID = 'fmLtkHkNzEf'; // Views.is_default (checkbox)
export const VIEWS_IS_CUSTOM_FIELD_ID = 'ffzWHnC5226'; // Views.is_custom (checkbox)
export const VIEWS_CREATED_BY_FIELD_ID = 'f2wpAXqn9Hv'; // Views.created_by (single_line_text)
export const VIEWS_EMPLOYEE_ID_FIELD_ID = 'f9oh2qLHw69'; // Views.employee_id (linked_record)

// Pay Period Templates fields
export const PAY_PERIOD_TEMPLATES_NAME_FIELD_ID = 'fcTwZrzCV3s'; // Pay Period Templates.Name (single_line_text)
export const PAY_PERIOD_TEMPLATES_DEPARTMENT_ID_FIELD_ID = 'fiunMgBrrC9'; // Pay Period Templates.department_id (linked_record)
export const PAY_PERIOD_TEMPLATES_PERIOD_NUMBER_FIELD_ID = 'faiQsBfwJtT'; // Pay Period Templates.period_number (number)
export const PAY_PERIOD_TEMPLATES_START_DAY_FIELD_ID = 'fjkdULQiY68'; // Pay Period Templates.start_day (number)
export const PAY_PERIOD_TEMPLATES_END_DAY_FIELD_ID = 'f6GFoDwhiuS'; // Pay Period Templates.end_day (number)
export const PAY_PERIOD_TEMPLATES_PAYOUT_DAY_FIELD_ID = 'fn8tD3dpDnQ'; // Pay Period Templates.payout_day (single_line_text)
export const PAY_PERIOD_TEMPLATES_PAYOUT_MONTH_OFFSET_FIELD_ID = 'fxzeXzvBGt2'; // Pay Period Templates.payout_month_offset (number)
export const PAY_PERIOD_TEMPLATES_IS_ACTIVE_FIELD_ID = 'f26NBqb2bqj'; // Pay Period Templates.is_active (checkbox)

/**
 * Helper function to get table ID by name
 */
export function getTableId(tableName: string): string | undefined {
  return filloutConfig.tables[tableName]?.id;
}

/**
 * Helper function to get field ID by table and field name
 */
export function getFieldId(tableName: string, fieldName: string): string | undefined {
  return filloutConfig.tables[tableName]?.fields[fieldName];
}
