/**
 * Script to generate Fillout table and field ID configuration
 * 
 * This script queries the Fillout API to get all tables and fields,
 * then generates a TypeScript config file that maps table/field names to IDs.
 * 
 * Run with: npx tsx scripts/generate-fillout-config.ts
 * 
 * The generated file will be: lib/fillout-config.generated.ts
 */

import { writeFileSync } from 'fs';
import { join } from 'path';
import { readFileSync } from 'fs';

// Load environment variables
const envPath = join(process.cwd(), '.env.local');
try {
  const envFile = readFileSync(envPath, 'utf-8');
  envFile.split('\n').forEach(line => {
    const [key, ...valueParts] = line.split('=');
    if (key && valueParts.length > 0) {
      const value = valueParts.join('=').trim().replace(/^["']|["']$/g, '');
      if (value && !key.startsWith('#')) {
        process.env[key.trim()] = value;
      }
    }
  });
} catch (err) {
  console.warn('Could not load .env.local, using process.env');
}

const FILLOUT_BASE_URL = process.env.FILLOUT_BASE_URL || 'https://tables.fillout.com/api/v1/bases';
const FILLOUT_BASE_ID = process.env.FILLOUT_BASE_ID || 'aa7a307dc0a191a5';
const FILLOUT_API_TOKEN = process.env.FILLOUT_API_TOKEN || process.env.FILLOUT_API_KEY || '';

interface Field {
  id: string;
  name: string;
  type: string;
  order: number;
}

interface Table {
  id: string;
  name: string;
  fields: Field[];
}

interface Database {
  id: string;
  name: string;
  tables: Table[];
}

async function generateConfig() {
  if (!FILLOUT_API_TOKEN) {
    console.error('❌ FILLOUT_API_TOKEN not found in environment variables');
    console.error('   Please set FILLOUT_API_TOKEN in .env.local');
    process.exit(1);
  }

  try {
    console.log('🔍 Fetching database schema from Fillout API...');
    
    // Get database structure
    const url = `${FILLOUT_BASE_URL}/${FILLOUT_BASE_ID}`;
    const response = await fetch(url, {
      headers: {
        'Authorization': `Bearer ${FILLOUT_API_TOKEN}`,
      },
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`API error: ${response.status} ${response.statusText}\n${errorText}`);
    }

    const database: Database = await response.json();
    const tables = database.tables || [];

    if (tables.length === 0) {
      throw new Error('No tables found in database');
    }

    console.log(`✅ Found ${tables.length} tables\n`);

    // Generate TypeScript config file
    const configLines: string[] = [
      '/**',
      ' * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY',
      ' * ',
      ' * This file is generated by running: npx tsx scripts/generate-fillout-config.ts',
      ' * ',
      ' * Generated at: ' + new Date().toISOString(),
      ' * Database: ' + database.name + ' (' + database.id + ')',
      ' */',
      '',
      'export interface TableConfig {',
      '  id: string;',
      '  fields: Record<string, string>; // field name -> field ID',
      '}',
      '',
      'export interface FilloutConfig {',
      '  tables: Record<string, TableConfig>; // table name -> table config',
      '}',
      '',
      '/**',
      ' * Fillout database configuration',
      ' * Maps table names and field names to their IDs',
      ' */',
      'export const filloutConfig: FilloutConfig = {',
      '  tables: {',
    ];

    // Helper function to create a safe constant name from table/field name
    function toConstantName(name: string, prefix: string = ''): string {
      // Convert to uppercase, replace spaces/special chars with underscores
      let constant = name
        .replace(/[^a-zA-Z0-9]/g, '_')
        .replace(/_+/g, '_')
        .replace(/^_|_$/g, '')
        .toUpperCase();
      
      if (prefix) {
        constant = prefix + '_' + constant;
      }
      
      return constant;
    }

    // Add each table
    for (const table of tables) {
      const tableName = table.name;
      const tableId = table.id;
      const fields = table.fields || [];

      configLines.push(`    // ${tableName}`);
      configLines.push(`    '${tableName}': {`);
      configLines.push(`      id: '${tableId}',`);
      configLines.push(`      fields: {`);

      // Add each field
      for (const field of fields) {
        const fieldName = field.name;
        const fieldId = field.id;
        const fieldType = field.type;
        
        // Escape single quotes in field names
        const safeFieldName = fieldName.replace(/'/g, "\\'");
        
        configLines.push(`        '${safeFieldName}': '${fieldId}', // ${fieldType}`);
      }

      configLines.push(`      },`);
      configLines.push(`    },`);
      configLines.push('');
    }

    configLines.push('  },');
    configLines.push('};');
    configLines.push('');
    
    // Generate table ID constants
    configLines.push('/**');
    configLines.push(' * Table ID constants');
    configLines.push(' * Generated from Fillout database schema');
    configLines.push(' */');
    for (const table of tables) {
      const constantName = toConstantName(table.name, 'TABLE');
      configLines.push(`export const ${constantName}_ID = '${table.id}'; // ${table.name}`);
    }
    configLines.push('');
    
    // Generate field ID constants for commonly used tables
    // We'll generate constants for all fields, but organize by table
    configLines.push('/**');
    configLines.push(' * Field ID constants');
    configLines.push(' * Generated from Fillout database schema');
    configLines.push(' * Format: TABLE_NAME_FIELD_NAME_FIELD_ID');
    configLines.push(' */');
    
    for (const table of tables) {
      const tableConstant = toConstantName(table.name);
      const fields = table.fields || [];
      
      if (fields.length > 0) {
        configLines.push(`// ${table.name} fields`);
        for (const field of fields) {
          const fieldConstant = toConstantName(field.name);
          const constantName = `${tableConstant}_${fieldConstant}_FIELD_ID`;
          configLines.push(`export const ${constantName} = '${field.id}'; // ${table.name}.${field.name} (${field.type})`);
        }
        configLines.push('');
      }
    }
    
    configLines.push('/**');
    configLines.push(' * Helper function to get table ID by name');
    configLines.push(' */');
    configLines.push("export function getTableId(tableName: string): string | undefined {");
    configLines.push("  return filloutConfig.tables[tableName]?.id;");
    configLines.push('}');
    configLines.push('');
    configLines.push('/**');
    configLines.push(' * Helper function to get field ID by table and field name');
    configLines.push(' */');
    configLines.push("export function getFieldId(tableName: string, fieldName: string): string | undefined {");
    configLines.push("  return filloutConfig.tables[tableName]?.fields[fieldName];");
    configLines.push('}');
    configLines.push('');

    const configContent = configLines.join('\n');
    const outputPath = join(process.cwd(), 'lib', 'fillout-config.generated.ts');
    
    writeFileSync(outputPath, configContent, 'utf-8');
    
    console.log(`✅ Generated config file: ${outputPath}`);
    console.log(`\n📊 Summary:`);
    console.log(`   - Tables: ${tables.length}`);
    
    const totalFields = tables.reduce((sum, table) => sum + (table.fields?.length || 0), 0);
    console.log(`   - Fields: ${totalFields}`);
    
    console.log(`\n💡 Usage:`);
    console.log(`   import { getTableId, getFieldId } from '@/lib/fillout-config.generated';`);
    console.log(`   const tableId = getTableId('Employees');`);
    console.log(`   const fieldId = getFieldId('Employee Pay Rates', 'employee_id');`);
    console.log(`\n🔄 To regenerate, run: npx tsx scripts/generate-fillout-config.ts`);

  } catch (error: any) {
    console.error('❌ Error:', error.message);
    if (error.stack) {
      console.error(error.stack);
    }
    process.exit(1);
  }
}

generateConfig();
